<a href="https://colab.research.google.com/github/24f1002320/Deep-Learning/blob/main/Deep_Learningipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Preliminaries**


In [ ]:
import torch

In [ ]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
x.numel()

12

In [ ]:
x.size()

torch.Size([12])

In [ ]:
x = x.reshape(3,4)

In [ ]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
x = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
x

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
torch.arange(30).reshape(2,5,3) # (no of matrix , row, column)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],

        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]]])

In [ ]:
x[0:2]

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4]])

In [ ]:
x[-1]

tensor([4, 3, 2, 1])

In [ ]:
x[1,3] = 6 # x [row,col] = replacement element

In [ ]:
x

tensor([[2, 1, 4, 3],
        [1, 2, 3, 6],
        [4, 3, 2, 1]])

In [ ]:
x[1:,:] = 9
x

tensor([[2, 1, 4, 3],
        [9, 9, 9, 9],
        [9, 9, 9, 9]])

In [ ]:
torch.exp(x)

tensor([[7.3891e+00, 2.7183e+00, 5.4598e+01, 2.0086e+01],
        [8.1031e+03, 8.1031e+03, 8.1031e+03, 8.1031e+03],
        [8.1031e+03, 8.1031e+03, 8.1031e+03, 8.1031e+03]])

In [ ]:
x= torch.tensor([2,5,4,3,9])
y = torch.tensor([1,8,3,1,4])
x-y,x+y,x*y,x/y,x**y

(tensor([ 1, -3,  1,  2,  5]),
 tensor([ 3, 13,  7,  4, 13]),
 tensor([ 2, 40, 12,  3, 36]),
 tensor([2.0000, 0.6250, 1.3333, 3.0000, 2.2500]),
 tensor([     2, 390625,     64,      3,   6561]))

In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

torch.cat((X,Y),dim=0) # concatnate in row

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [ ]:
torch.cat((X,Y),dim=1) # concatnate in column

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [ ]:
X.sum(),Y.sum()

(tensor(66.), tensor(30.))

In [ ]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)

In [ ]:
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
# Saving Memory
before = id(y)
y = y + x
id(y) == before

False

In [ ]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 134213871220640
id(Z): 134213871220640


In [ ]:
before = id(X)
X += Y
id(X) == before

True

In [ ]:
a = X.numpy()
b = torch.from_numpy(a)
type(a),type(b)

(numpy.ndarray, torch.Tensor)

In [ ]:
a = torch.tensor([3.5])
a, a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

##  Exercises

`1. Run the code in this section. Change the conditional statement X == Yto X < Yor X >
Y, and then see what kind of tensor you can get.`

In [ ]:
X = torch.tensor([1,2,3,4])
Y = torch.tensor([5,6,7,8])
X == Y, X > Y, X < Y

(tensor([False, False, False, False]),
 tensor([False, False, False, False]),
 tensor([True, True, True, True]))

``2. Replace the two tensors that operate by element in the broadcasting mechanism with
other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?``

In [ ]:
A = torch.tensor([2, 3, 4])
B = torch.tensor([1, 3, 1])

B = np.ones((1,3,1)) * 2
print(B)
C = A * B
print(C.shape)


[[[2.]
  [2.]
  [2.]]]
torch.Size([1, 3, 3])


/tmp/ipython-input-3980349633.py:6: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  C = A * B


In [ ]:


# 3D tensor
A = torch.arange(24).reshape(2, 3, 4)
print("A shape:", A.shape)
print(A)

# 1D tensor
B = torch.tensor([10, 20, 30, 40])
print("\nB shape:", B.shape)
print(B)

# Broadcasting addition
C = A + B
print("\nC shape:", C.shape)
print(C)


A shape: torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

B shape: torch.Size([4])
tensor([10, 20, 30, 40])

C shape: torch.Size([2, 3, 4])
tensor([[[10, 21, 32, 43],
         [14, 25, 36, 47],
         [18, 29, 40, 51]],

        [[22, 33, 44, 55],
         [26, 37, 48, 59],
         [30, 41, 52, 63]]])


# **Data Preprocessing**

In [ ]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True) # creates directories (also creates parent folders if needed).
data_file = os.path.join('..', 'data', 'house_tiny.csv') # create a csv file inside data directories.
with open(data_file, 'w') as f:

  f.write('''NumRooms,RoofType,Price
  NA,NA,127500
  2,NA,106000
  4,Slate,178100
  NA,NA,140000''')

In [ ]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


In [ ]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


In [ ]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


In [ ]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

## Exercises

`1. Try loading datasets, e.g., Abalone from the UCI Machine Learning Repository50 and
inspect their properties. What fraction of them has missing values? What fraction of
the variables is numerical, categorical, or text?`

In [ ]:
data = pd.read_csv('/content/abalone.data')
data.head()

M  0.455  0.365  0.095   0.514  0.2245   0.101   0.15  15
0  M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.070   7
1  F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.210   9
2  M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.155  10
3  I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.055   7
4  I  0.425  0.300  0.095  0.3515  0.1410  0.0775  0.120   8

In [ ]:
data.isnull().sum()

M         0
0.455     0
0.365     0
0.095     0
0.514     0
0.2245    0
0.101     0
0.15      0
15        0
dtype: int64

# **Linear Algebra**